### PR TITLE
fix #5 issue with unregister method

### LINKED ISSUE #5: Doesn't unregister fields
Sandbox example:
https://codesandbox.io/s/doesnt-unregister-h3sf4

Click submit to see that fields of the removed fields are still present. I believe `unregister` method inside `RHFInput` is `undefined`.

### PR DESCRIPTION
**Pull request by GProst**

### CODE REVIEW

**Comment by bluebill1049** [comment]
thanks @GProst i have made register to return unregister but had a bug, which i am fixing here: 
https://github.com/react-hook-form/react-hook-form/pull/570/files

**Comment by GProst** [comment]
@bluebill1049 great! 💪
Closing this then

**Comment by bluebill1049** [comment]
thanks heaps @GProst

**Comment by bluebill1049** [comment]
after careful thoughts in think its safer with this approach

**Pull request merged**
