### PR TITLE
Fix wrong logic of check target.chcked

### PR DESCRIPTION
**Pull request by iamchanii**
Caused by #42

### CODE REVIEW

**Comment by iamchanii** [comment]
Something wrong, sorry I will create a new PR.

**Comment by iamchanii** [comment]
Maybe I got a confuse by local cache. 😢@bluebill1049 Can you review again?

**Comment by bluebill1049** [comment]
this is right now

**Comment by bluebill1049** [comment]
try this beta: `1.1.10-beta.2` let me know if this fix it and we can release it

**Comment by iamchanii** [comment]
My product is working and pass all tests, also codesandbox too!

**Comment by bluebill1049** [comment]
Nice will release it after lunch

**Pull request merged**
